import { ref, watch } from 'vue'

const isDark = ref(false)

export function useTheme() {
  function applyTheme(dark) {
    const root = document.documentElement
    if (dark) {
      root.classList.add('theme-soft-dark')
      root.classList.remove('theme-light')
      root.style.setProperty('--bg-primary', '#071a0f')
      root.style.setProperty('--bg-secondary', '#0c2a18')
      root.style.setProperty('--bg-card', '#112b1e')
      root.style.setProperty('--bg-card-hover', '#163324')
      root.style.setProperty('--bg-input', '#0c2a18')
      root.style.setProperty('--bg-section', '#0a2015')
      root.style.setProperty('--bg-nav', 'rgba(10, 32, 21, 0.95)')
      root.style.setProperty('--text-primary', '#ecfdf5')
      root.style.setProperty('--text-secondary', '#a7f3d0')
      root.style.setProperty('--text-muted', '#6ee7b7')
      root.style.setProperty('--text-dark', '#064e3b')
      root.style.setProperty('--text-invert', '#071a0f')
      root.style.setProperty('--border-color', '#14532d')
      root.style.setProperty('--border-muted', '#166534')
      root.style.setProperty('--border-input', '#166534')
      root.style.setProperty('--brand-alpha', 'rgba(34, 197, 94, 0.12)')
      root.style.setProperty('--brand-alpha-hover', 'rgba(34, 197, 94, 0.2)')
      root.style.setProperty('--shadow-color', 'rgba(6, 78, 59, 0.5)')
      root.style.setProperty('--shadow-card', '0 2px 8px rgba(0,0,0,0.3)')
      root.style.setProperty('--shadow-lg', '0 10px 30px rgba(6, 78, 59, 0.4)')
      root.style.setProperty('--nav-bg', 'rgba(10, 32, 21, 0.95)')
      root.style.setProperty('--nav-border', '#14532d')
      root.style.setProperty('--card-bg', '#112b1e')
      root.style.setProperty('--card-border', '#166534')
      root.style.setProperty('--card-hover-bg', '#163324')
      root.style.setProperty('--card-hover-border', '#22c55e')
      root.style.setProperty('--input-bg', '#0c2a18')
      root.style.setProperty('--input-border', '#166534')
      root.style.setProperty('--input-text', '#d1fae5')
      root.style.setProperty('--input-placeholder', '#6ee7b7')
      root.style.setProperty('--btn-primary-bg', '#16a34a')
      root.style.setProperty('--btn-primary-hover', '#15803d')
      root.style.setProperty('--btn-primary-shadow', 'rgba(34, 197, 94, 0.3)')
      root.style.setProperty('--btn-secondary-bg', '#163324')
      root.style.setProperty('--btn-secondary-text', '#d1fae5')
      root.style.setProperty('--btn-secondary-border', '#166534')
      root.style.setProperty('--btn-secondary-hover-bg', '#1a3d2c')
      root.style.setProperty('--btn-ghost-text', '#6ee7b7')
      root.style.setProperty('--btn-ghost-hover-bg', 'rgba(34, 197, 94, 0.1)')
      root.style.setProperty('--text-error', '#fca5a5')
      root.style.setProperty('--text-success', '#4ade80')
      root.style.setProperty('--step-active-bg', '#16a34a')
      root.style.setProperty('--step-active-text', '#ffffff')
      root.style.setProperty('--step-inactive-bg', '#14532d')
      root.style.setProperty('--step-inactive-text', '#6ee7b7')
    } else {
      root.classList.add('theme-light')
      root.classList.remove('theme-soft-dark')
      root.style.setProperty('--bg-primary', '#fafaf8')
      root.style.setProperty('--bg-secondary', '#f0fdf4')
      root.style.setProperty('--bg-card', '#ffffff')
      root.style.setProperty('--bg-card-hover', '#f0fdf4')
      root.style.setProperty('--bg-input', '#ffffff')
      root.style.setProperty('--bg-section', '#f0fdf4')
      root.style.setProperty('--bg-nav', '#ffffff')
      root.style.setProperty('--text-primary', '#1c1917')
      root.style.setProperty('--text-secondary', '#374151')
      root.style.setProperty('--text-muted', '#6b7280')
      root.style.setProperty('--text-dark', '#f0fdf4')
      root.style.setProperty('--text-invert', '#1c1917')
      root.style.setProperty('--border-color', '#d1fae5')
      root.style.setProperty('--border-muted', '#a7f3d0')
      root.style.setProperty('--border-input', '#d1d5db')
      root.style.setProperty('--brand-alpha', 'rgba(22, 163, 74, 0.08)')
      root.style.setProperty('--brand-alpha-hover', 'rgba(22, 163, 74, 0.12)')
      root.style.setProperty('--shadow-color', 'rgba(22, 101, 52, 0.1)')
      root.style.setProperty('--shadow-card', '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)')
      root.style.setProperty('--shadow-lg', '0 10px 25px rgba(22, 101, 52, 0.12)')
      root.style.setProperty('--nav-bg', '#ffffff')
      root.style.setProperty('--nav-border', '#e5e7eb')
      root.style.setProperty('--card-bg', '#ffffff')
      root.style.setProperty('--card-border', '#e5e7eb')
      root.style.setProperty('--card-hover-bg', '#f0fdf4')
      root.style.setProperty('--card-hover-border', '#86efac')
      root.style.setProperty('--input-bg', '#ffffff')
      root.style.setProperty('--input-border', '#d1d5db')
      root.style.setProperty('--input-text', '#1c1917')
      root.style.setProperty('--input-placeholder', '#9ca3af')
      root.style.setProperty('--btn-primary-bg', '#16a34a')
      root.style.setProperty('--btn-primary-hover', '#15803d')
      root.style.setProperty('--btn-primary-shadow', 'rgba(22, 163, 74, 0.25)')
      root.style.setProperty('--btn-secondary-bg', '#ffffff')
      root.style.setProperty('--btn-secondary-text', '#374151')
      root.style.setProperty('--btn-secondary-border', '#d1d5db')
      root.style.setProperty('--btn-secondary-hover-bg', '#f9fafb')
      root.style.setProperty('--btn-ghost-text', '#6b7280')
      root.style.setProperty('--btn-ghost-hover-bg', 'rgba(0,0,0,0.04)')
      root.style.setProperty('--text-error', '#ef4444')
      root.style.setProperty('--text-success', '#16a34a')
      root.style.setProperty('--step-active-bg', '#16a34a')
      root.style.setProperty('--step-active-text', '#ffffff')
      root.style.setProperty('--step-inactive-bg', '#e5e7eb')
      root.style.setProperty('--step-inactive-text', '#9ca3af')
    }
  }

  function toggle() {
    isDark.value = !isDark.value
    localStorage.setItem('vetdesk-theme', isDark.value ? 'dark' : 'light')
    applyTheme(isDark.value)
  }

  function init() {
    const saved = localStorage.getItem('vetdesk-theme')
    isDark.value = saved === 'dark'
    applyTheme(isDark.value)
  }

  return { isDark, toggle, init }
}
